=== kphannan/OpenLCB/scratchpads/jkueneman/NodeExplorer/tests/schema/testmatrix.xsd
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet href="schema2xhtml.xsl" type="text/xsl"?>

<!-- XML Schema for OpenLCB Test Matrix definition     -->

<xs:schema xmlns:xs  ="http://www.w3.org/2001/XMLSchema"
           xmlns:xsi ="http://www.w3.org/2001/XMLSchema-instance"
           >

    <xs:element name="TestMatrix">
      <xs:annotation>
        <xs:documentation>
          This is the schema for Test Matrix definition files
        </xs:documentation>
      </xs:annotation>
      <xs:complexType>
        <xs:sequence>

          <xs:element name="Test" minOccurs="1" maxOccurs="unbounded">
            <xs:annotation>
              <xs:documentation>
                Describe a specific test
              </xs:documentation>
            </xs:annotation>
            <xs:complexType>
              <xs:sequence>

                <xs:element name="Name" minOccurs="1" maxOccurs="1"/>

                <xs:element name="Description" minOccurs="0" maxOccurs="1"/>

                <xs:element name="SpecDoc" minOccurs="1" maxOccurs="1"/>

                <xs:element name="Classname" minOccurs="0" maxOccurs="unbounded"/>

                <xs:element name="Enabled" minOccurs="0" maxOccurs="1"/>

                <xs:element name="TestObjective" minOccurs="1" maxOccurs="unbounded">
                  <xs:annotation>
                    <xs:documentation>
                      Element that identifies objective and corresponding results for this test.
                    </xs:documentation>
                  </xs:annotation>
                  <xs:complexType>
                    <xs:sequence>
                      <xs:element name="Objective" minOccurs="1" maxOccurs="1"/>
                      <xs:element name="Results" minOccurs="1" maxOccurs="1"/>
                    </xs:sequence>
                  </xs:complexType>
                </xs:element>

              </xs:sequence>
            </xs:complexType>
          </xs:element>

        </xs:sequence>
      </xs:complexType>
    </xs:element>
</xs:schema>

=== kphannan/OpenLCB/prototypes/xml/testMatrixSample.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="xslt/testmatrix.xsl"?>

<TestMatrix xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://openlcb.org/trunk/prototypes/xml/schema/testmatrix.xsd">
  <Test>
    <Name>IdentifyNodes</Name>
    <Description>Identifies all nodes on the network using VerifyNodeID</Description>
    <SpecDoc>"OpenLCB Message Network" Paragraph 2.6.2</SpecDoc>
    <Classname>TTestVerifyNodeID</Classname>
    <Enabled>True</Enabled>
    <TestObjective>
      <Objective>Send global Verify Node ID Message Network Layer Message</Objective>
      <Results>Verified Node ID from all nodes on the network</Results>
    </TestObjective>
  </Test>
  <Test>
    <Name>AliasMapEnquiry</Name>
    <Description>Test the Alias Map Enquiry Message</Description>
    <SpecDoc>"OpenLCB-CAN Frame Transfer Paragraph 6.2.3</SpecDoc>
    <Classname>TTestAliasMapEnquiry</Classname>
    <Enabled>False</Enabled>
    <TestObjective>
      <Objective>Send AME message with Full Node ID of Node Under Test as CAN data payload</Objective>
      <Results>Receive Alias Map Definition (AMD) from node matching the Full Node ID sent</Results>
    </TestObjective>
    <TestObjective>
      <Objective>Send AME message with an empty data payload</Objective>
      <Results>Alias Map Definitions (AMD) from all nodes on network</Results>
    </TestObjective>
    <TestObjective>
      <Objective>Send AME message with Full Node ID of no known node on the network in the CAN data payload</Objective>
      <Results>No Response</Results>
    </TestObjective>
  </Test>
</TestMatrix>

=== kphannan/OpenLCB/scratchpads/jkueneman/NodeExplorer/tests/testMatrixSample.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="xslt/testmatrix.xsl"?>
<TestMatrix xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://openlcb.org/trunk/prototypes/xml/schema/testmatrix.xsd">
  <Test>
    <Name>Identify Nodes</Name>
    <Description>Identifies all nodes on the network using VerifyNodeID</Description>
    <Classname>TTestVerifyNodesID</Classname>
    <Enabled>True</Enabled>
    <TestObjective>
      <SpecDoc>"OpenLCB Message Network" Paragraph 2.6.2</SpecDoc>
      <Objective>Send global Verify Node ID Message Network Layer Message</Objective>
      <Results>Verified Node ID from all nodes on the network</Results>
    </TestObjective>
  </Test>
  <Test>
    <Name>Alias Map Enquiry</Name>
    <Description>Tests target for correct implementation of the Alias Map Enquiry (AME) Message</Description>    
    <Classname>TTestAliasMapEnquiry</Classname>
    <Enabled>True</Enabled>
    <TestObjective>
      <SpecDoc>"OpenLCB-CAN Frame Transfer Paragraph 6.2.3</SpecDoc>
      <Objective>Send AME message with no CAN data</Objective>
      <Results>Receive Alias Map Definition (AMD) from all nodes on the network</Results>
    </TestObjective>
    <TestObjective>
      <SpecDoc>"OpenLCB-CAN Frame Transfer Paragraph 6.2.3</SpecDoc>
      <Objective>Send AME message with Full Node ID of node under test in the data payload</Objective>
      <Results>Receive Alias Map Definition (AMD) from node matching the Full Node ID in the data payload</Results>
    </TestObjective>
    <TestObjective>
      <SpecDoc>"OpenLCB-CAN Frame Transfer Paragraph 6.2.3</SpecDoc>
      <Objective>Send AME message with Full Node ID of non existent node in the data payload</Objective>
      <Results>No reply</Results>
    </TestObjective>
  </Test>
  <Test>
    <Name>Verify Node </Name>
    <Description>Tests target for correct implementation of the VerifyNodeID message</Description>    
    <Classname>TTestVerifyNodeID</Classname>
    <Enabled>True</Enabled>
    <TestObjective>
      <SpecDoc>"OpenLCB Message Network" Paragraph 2.6.2</SpecDoc>
      <Objective>Send Global Identify Nodes message</Objective>
      <Results>All nodes on network reply with the target of interest included</Results>
    </TestObjective>
    <TestObjective>
      <SpecDoc>"OpenLCB Message Network" Paragraph 2.6.2</SpecDoc>
      <Objective>Send Identify Nodes message with Full Node ID of node under test in data payload</Objective>
      <Results>Verified Node ID from target node on the network</Results>
    </TestObjective>
    <TestObjective>
      <Objective>Send Identify Nodes message with Full Node ID of non existent node in the data payload</Objective>
      <Results>No reply expected</Results>
    </TestObjective>
    <TestObjective>
      <SpecDoc>"OpenLCB Message Network" Paragraph 2.6.2</SpecDoc>
      <Objective>Send Addressed Identify Nodes message with Full Node ID in the data payload</Objective>
      <Results>Verified Node ID from target node on the network</Results>
    </TestObjective>
    <TestObjective>
      <SpecDoc>"OpenLCB Message Network" Paragraph 2.6.2</SpecDoc>
      <Objective>Send Addressed Identify Nodes message with Full Node ID in the data payload to the incorrect alias address</Objective>
      <Results> No reply expected</Results>
    </TestObjective>
  </Test>
  <Test>
    <Name>Protocol Identification Protocol (PIP)</Name>
    <Description>Requests what protocols a node supports, optional but recommended implementation</Description>    
    <Classname>TTestProtocolSupport</Classname>
    <Enabled>True</Enabled>
    <TestObjective>
      <SpecDoc>"Protocol Identification Protocol"</SpecDoc>
      <Objective>Test that NUT responds to PIP message addressed to it</Objective>
      <Results>Receive protocols supported by the node (or no response if does not support)</Results>
    </TestObjective>
    <TestObjective>
      <SpecDoc>"Protocol Identification Protocol"</SpecDoc>
      <Objective>Test that NUT does not respond to PIP message addressed to another</Objective>
      <Results>No response</Results>
    </TestObjective>
    <TestObjective>
      <SpecDoc>"Protocol Identification Protocol"</SpecDoc>
      <Objective>Test that NUT understands start and end bits in PIP message</Objective>
      <Results>One response</Results>
    </TestObjective>
  </Test>
</TestMatrix>

=== kphannan/OpenLCB/scratchpads/jkueneman/Node Explorer/tests/testMatrixSample.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="xslt/testmatrix.xsl"?>
<TestMatrix xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://openlcb.org/trunk/prototypes/xml/schema/testmatrix.xsd">
  <Test>
    <Name>Identify Nodes</Name>
    <Description>Identifies all nodes on the network using VerifyNodeID</Description>
    <SpecDoc>"OpenLCB Message Network" Paragraph 2.6.2</SpecDoc>
    <Classname>TTestVerifyNodesID</Classname>
    <Enabled>True</Enabled>
    <TestObjective>
      <Objective>Send global Verify Node ID Message Network Layer Message</Objective>
      <Results>Verified Node ID from all nodes on the network</Results>
    </TestObjective>
  </Test>
  <Test>
    <Name>Alias Map Enquiry</Name>
    <Description>Tests target for correct implementation of the Alias Map Enquiry (AME) Message</Description>
    <SpecDoc>"OpenLCB-CAN Frame Transfer Paragraph 6.2.3</SpecDoc>
    <Classname>TTestAliasMapEnquiry</Classname>
    <Enabled>True</Enabled>
    <TestObjective>
      <Objective>Send AME message with no CAN data</Objective>
      <Results>Receive Alias Map Definition (AMD) from all nodes on the network</Results>
    </TestObjective>
    <TestObjective>
      <Objective>Send AME message with Full Node ID of node under test in the data payload</Objective>
      <Results>Receive Alias Map Definition (AMD) from node matching the Full Node ID in the data payload</Results>
    </TestObjective>
    <TestObjective>
      <Objective>Send AME message with Full Node ID of non existent node in the data payload</Objective>
      <Results>No reply</Results>
    </TestObjective>
  </Test>
  <Test>
    <Name>Verify Node </Name>
    <Description>Tests target for correct implementation of the VerifyNodeID message</Description>
    <SpecDoc>"OpenLCB Message Network" Paragraph 2.6.2</SpecDoc>
    <Classname>TTestVerifyNodeID</Classname>
    <Enabled>True</Enabled>
    <TestObjective>
      <Objective>Send Global Identify Nodes message</Objective>
      <Results>All nodes on network reply with the target of interest included</Results>
    </TestObjective>
    <TestObjective>
      <Objective>Send Identify Nodes message with Full Node ID of node under test in data payload</Objective>
      <Results>Verified Node ID from target node on the network</Results>
    </TestObjective>
    <TestObjective>
      <Objective>Send Identify Nodes message with Full Node ID of non existent node in the data payload</Objective>
      <Results>No reply expected</Results>
    </TestObjective>
    <TestObjective>
      <Objective>Send Addressed Identify Nodes message with Full Node ID in the data payload</Objective>
      <Results>Verified Node ID from target node on the network</Results>
    </TestObjective>
    <TestObjective>
      <Objective>Send Addressed Identify Nodes message with Full Node ID in the data payload to the incorrect alias address</Objective>
      <Results> No reply expected</Results>
    </TestObjective>
  </Test>
  <Test>
    <Name>Protocol Identification Protocol (PIP)</Name>
    <Description>Requests what protocols a node supports, optional but recommended implementation</Description>
    <SpecDoc>"Protocol Identification Protocol" Paragraph 6</SpecDoc>
    <Classname>TTestProtocolSupport</Classname>
    <Enabled>True</Enabled>
    <TestObjective>
      <Objective>Send addressed Protocol Identification Protocol message</Objective>
      <Results>Receive protocols supported by the node (or no response if does not support)</Results>
    </TestObjective>
  </Test>
</TestMatrix>
