=== kphannan/OpenLCB/prototypes/xml/schema/cdi.xsd
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet href="schema2xhtml.xsl" type="text/xsl"?>

<!-- XML Schema for OpenLCB Configuration Description Information (CDI)     -->

<xs:schema xmlns:xs  ="http://www.w3.org/2001/XMLSchema"
           xmlns:xsi ="http://www.w3.org/2001/XMLSchema-instance"
           >

   <xs:complexType name="mapType">
       <xs:sequence>
              <xs:element name="name" minOccurs="0" maxOccurs="1"/>
              <xs:element name="description" minOccurs="0" maxOccurs="1"/>
              <xs:element name="relation" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="property" minOccurs="1" maxOccurs="1"/>
                    <xs:element name="value" minOccurs="1" maxOccurs="1"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
       </xs:sequence>
    </xs:complexType>

   <xs:complexType name="groupType">
            <xs:sequence>
              <xs:element name="name" minOccurs="0" maxOccurs="1"/>
              <xs:element name="description" minOccurs="0" maxOccurs="1"/>
              <xs:choice minOccurs="0" maxOccurs="unbounded">
                  <xs:annotation>
                    <xs:documentation>
                      Allows any sequence of the contained element types
                    </xs:documentation>
                  </xs:annotation>
                  <xs:element name="group" type="groupType" minOccurs="0" maxOccurs="1"/>
                  <xs:element name="bit" type="bitType" minOccurs="0" maxOccurs="1"/>
                  <xs:element name="int" type="intType" minOccurs="0" maxOccurs="1"/>
                  <xs:element name="eventid" type="eventidType" minOccurs="0" maxOccurs="1"/>
              </xs:choice>
            </xs:sequence>
            <xs:attribute name="offset" type="xs:int" />
            <xs:attribute name="replication" type="xs:int" />
    </xs:complexType>

   <xs:complexType name="eventidType">
            <xs:sequence>
              <xs:element name="name" minOccurs="0" maxOccurs="1"/>
              <xs:element name="description" minOccurs="0" maxOccurs="1"/>
              <xs:element name="map" type="mapType" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
    </xs:complexType>

   <xs:complexType name="intType">
            <xs:sequence>
              <xs:element name="name" minOccurs="0" maxOccurs="1"/>
              <xs:element name="description" minOccurs="0" maxOccurs="1"/>
              <xs:element name="min" minOccurs="0" maxOccurs="1"/>
              <xs:element name="max" minOccurs="0" maxOccurs="1"/>
              <xs:element name="default" minOccurs="0" maxOccurs="1"/>
              <xs:element name="map" type="mapType" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
            <xs:attribute name="size" type="xs:int" />
    </xs:complexType>

   <xs:complexType name="bitType">
            <xs:sequence>
              <xs:element name="name" minOccurs="0" maxOccurs="1"/>
              <xs:element name="description" minOccurs="0" maxOccurs="1"/>
              <xs:element name="map" type="mapType" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
            <xs:attribute name="size" type="xs:int" />
    </xs:complexType>

    <xs:element name="cdi">
      <xs:annotation>
        <xs:documentation>
          This is the schema for Configuration Description Information (cdi)
        </xs:documentation>
      </xs:annotation>
      <xs:complexType>
        <xs:sequence>

          <xs:element name="identification" minOccurs="0" maxOccurs="1">
            <xs:annotation>
              <xs:documentation>
                Common first element to identify the decoder
              </xs:documentation>
            </xs:annotation>
            <xs:complexType>
              <xs:sequence>
                <xs:element name="manufacturer" minOccurs="0" maxOccurs="1"/>
                <xs:element name="model" minOccurs="0" maxOccurs="1"/>
                <xs:element name="hardwareVersion" minOccurs="0" maxOccurs="1"/>
                <xs:element name="softwareVersion" minOccurs="0" maxOccurs="1"/>
                <xs:element name="map" type="mapType" minOccurs="0" maxOccurs="1"/>
              </xs:sequence>
            </xs:complexType>
          </xs:element>

          <xs:element name="segment" minOccurs="0" maxOccurs="unbounded">
            <xs:annotation>
              <xs:documentation>
                Define the contents of a memory space
              </xs:documentation>
            </xs:annotation>
            <xs:complexType>
              <xs:sequence>
                <xs:element name="name" minOccurs="0" maxOccurs="1"/>
                <xs:element name="description" minOccurs="0" maxOccurs="1"/>
                <xs:choice minOccurs="0" maxOccurs="unbounded">
                  <xs:annotation>
                    <xs:documentation>
                      Allows any sequence of the contained element types
                    </xs:documentation>
                  </xs:annotation>
                  <xs:element name="group" type="groupType" minOccurs="0" maxOccurs="1"/>
                  <xs:element name="bit" type="bitType" minOccurs="0" maxOccurs="1"/>
                  <xs:element name="int" type="intType" minOccurs="0" maxOccurs="1"/>
                  <xs:element name="eventid" type="eventidType" minOccurs="0" maxOccurs="1"/>
                </xs:choice>
              </xs:sequence>
              <xs:attribute name="space" type="xs:int" />
              <xs:attribute name="origin" type="xs:int" />
            </xs:complexType>
          </xs:element>

        </xs:sequence>
      </xs:complexType>
    </xs:element>
</xs:schema>

=== kphannan/OpenLCB/prototypes/C/tch_tech_16P_24C/cdi_16_24_PC.xml
<?xml version='1.0'?>
<?xml-stylesheet type='text/xsl' href='http://openlcb.org/trunk/prototypes/xml/xslt/cdi.xsl'?>
<cdi xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:noNamespaceSchemaLocation='http://openlcb.org/trunk/prototypes/xml/schema/cdi.xsd'>

<identification>
    <manufacturer>TCH Technology</manufacturer>
    <model>OpenLCB 16 in 24 out P/C node</model>
    <hardwareVersion>0.1.2</hardwareVersion>
    <softwareVersion>0.6.0</softwareVersion>
</identification>

<segment origin='0' space='253'>
    <group offset='876'>
        <name>User Identification</name>
        <description>Lets the user add his own description</description>
        <string size='20'>
            <name>Node Name</name>
        </string>
        <string size='26'>
            <name>Node Description</name>
        </string>
    </group>
</segment>

<segment origin='10' space='253'>
    <group replication='24'>
        <name>Outputs</name>
        <repname>Output</repname>
        <string size='16' offset='920'>
            <name>Description</name>
        </string>
        <eventid offset='-934' ><!-- forward 150, add 16, back 166, then forward 2-->
            <name>Activation Event</name>
        </eventid>
        <eventid offset='2' >
            <name>Inactivation Event</name>
        </eventid>
    </group>
    <group replication='16'>
        <name>Inputs</name>
        <repname>Input</repname>
        <string size='16' offset='920'>
            <name>Description</name>
        </string>
        <eventid offset='-934' ><!-- forward 150, add 16, back 166, then forward 2-->
            <name>Set Event</name>
        </eventid>
        <eventid offset='2' >
            <name>Reset Event</name>
        </eventid>
    </group>
</segment>

<segment origin='0' space='253'>
    <int size='4'>
        <name>Reset</name>
        <description>Controls reloading and clearing node memory. Board must be restarted for this to take effect.</description>
        <map>
            <relation><property>3998572261</property><value>(No reset)</value></relation>
            <relation><property>0</property><value>Reset all to defaults</value></relation>
            <relation><property>3998561228</property><value>Reset EventIDs to new defaults</value></relation>
        </map>
    </int>
</segment>

</cdi>

=== kphannan/OpenLCB/prototypes/C/OlcbBasicNode/cdi.xml
<?xml version='1.0'?>
<?xml-stylesheet type='text/xsl' href='xslt/cdi.xsl'?>
<cdi xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:noNamespaceSchemaLocation='http://openlcb.org/trunk/prototypes/xml/schema/cdi.xsd'>

<identification>
    <manufacturer>OpenLCB</manufacturer>
    <model>OlcbBasicNode</model>
    <hardwareVersion>1.0</hardwareVersion>
    <softwareVersion>0.4</softwareVersion>
</identification>

<segment origin='0' space='253'>
    <group offset='77'>
        <name>User Identification</name>
        <description>Lets the user add his own description</description>
        <string size='12'>
            <name>Node Name</name>
        </string>
        <string size='20'>
            <name>Node Description</name>
        </string>
    </group>
</segment>

<segment origin='10' space='253'>
    <group replication='2'>
        <description>Input Pin</description>
        <eventid offset='2' >
            <name>Activation Event</name>
        </eventid>
        <eventid offset='2' >
            <name>Inactivation Event</name>
        </eventid>
    </group>
    <group replication='2'>
        <description>Output Pin</description>
        <eventid offset='2' >
            <name>Set Event</name>
        </eventid>
        <eventid offset='2' >
            <name>Reset Event</name>
        </eventid>
    </group>
</segment>

<segment origin='0' space='253'>
    <int size='4'>
        <name>Reset</name>
        <description>Controls reloading and clearing node memory. Board must be restarted for this to take effect.</description>
        <map>
            <relation><property>0xEE555EE5</property><value>(No reset)</value></relation>
            <relation><property>0</property><value>Reset all to defaults</value></relation>
            <relation><property>0xEE5533CC</property><value>Reset EventIDs to new defaults</value></relation>
        </map>
    </int>
    <int size='6'>
        <name>NodeID</name>
        <description>Set the board's NodeID. Board must be restarted for this to take effect.</description>
    </int>
</segment>

</cdi>

=== kphannan/OpenLCB/prototypes/C/OlcbStarLibraries/OlcbBasicNode/cdi.xml
<?xml version='1.0'?>
<?xml-stylesheet type='text/xsl' href='http://openlcb.org/trunk/prototypes/xml/xslt/cdi.xsl'?>
<cdi xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:noNamespaceSchemaLocation='http://openlcb.org/trunk/prototypes/xml/schema/cdi.xsd'>

<identification>
    <manufacturer>OpenLCB</manufacturer>
    <model>OlcbBasicNode</model>
    <hardwareVersion>1.0</hardwareVersion>
    <softwareVersion>0.4</softwareVersion>
</identification>

<segment origin='0' space='253'>
    <name>Node ID</name>
    <description>User-provided description of the node</description>
    <group offset='94'>
        <string size='20'>
            <name>Node Name</name>
        </string>
        <string size='24'>
            <name>Node Description</name>
        </string>
    </group>
</segment>

<segment origin='10' space='253'>
    <name>I/O Events</name>
    <description>Define events associated with input and output pins</description>
    <group replication='2'>
        <name>Inputs</name>
        <repname>Input</repname>
        <string size='16' offset='150'>
            <name>Description</name>
        </string>
        <eventid offset='-164' ><!-- forward 150, add 16, back 166, then forward 2-->
            <name>Activation Event</name>
        </eventid>
        <eventid offset='2' >
            <name>Inactivation Event</name>
        </eventid>
    </group>
    <group replication='2'>
        <name>Outputs</name>
        <repname>Output</repname>
        <string size='16' offset='150'>
            <name>Description</name>
        </string>
        <eventid offset='-164' ><!-- forward 150, add 16, back 166, then forward 2-->
            <name>Set Event</name>
        </eventid>
        <eventid offset='2' >
            <name>Reset Event</name>
        </eventid>
    </group>
</segment>

<segment origin='0' space='253'>
    <name>Reset</name>
    <description>Controls reloading and clearing node memory. Board must be restarted for this to take effect.</description>
    <int size='4'>
        <map>
            <relation><property>3998572261</property><value>(No reset)</value></relation>
            <relation><property>3998561228</property><value>User clear: New default EventIDs, blank strings</value></relation>
            <relation><property>0</property><value>Mfg clear: Reset all, including Node ID</value></relation>
        </map>
    </int>
</segment>

</cdi>

=== kphannan/OpenLCB/scratchpads/jkueneman/OPStack/Projects/NCEBridge/Templates/NMRAnetNceAdapter.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://openlcb.org/trunk/prototypes/xml/xslt/cdi.xsl"?>
<cdi xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://openlcb.org/trunk/specs/schema/cdi.xsd">
  <identification>
    <manufacturer>Mustangpeak</manufacturer>
    <model>NA100</model>
    <hardwareVersion>1.0</hardwareVersion>
    <softwareVersion>0.2</softwareVersion>
    <map>
      <relation>
        <property>Description</property>
        <value>Mustangpeak NCE Adapter Node</value>
      </relation>
      <relation>
        <property>Status</property>
        <value>Prototype</value>
      </relation>
    </map>
  </identification>
  <acdi fixed="1" var="1"/>
  <segment origin="0" space="253">
    <name>Options</name>
    <description>Options for the NCE to OpenLCB Adapter</description>
    <group offset="1">
      <name>User Data</name>
      <description>Add your own unique node info here</description>
      <string size="63">
        <name>User Name</name>
      </string>
      <string size="64">
        <name>User Description</name>
      </string>
      <int>
        <name>Speed Steps</name>
        <description>DCC speed steps used to allocate a DCC Train</description>
        <map>
          <relation>
            <property>0</property>
            <value>14 Steps</value>
          </relation>
          <relation>
            <property>1</property>
            <value>28 Steps</value>
          </relation>
          <relation>
            <property>2</property>
            <value>128 Steps</value>
          </relation>
        </map>
      </int>
      <int>
        <name>Address Type</name>
        <description>Allocate a DCC train with either short or long address</description>
        <map>
          <relation>
            <property>0</property>
            <value>Short</value>
          </relation>
          <relation>
            <property>1</property>
            <value>Long</value>
          </relation>
        </map>
      </int>
    </group>
  </segment>
  <segment origin="0" space="252">
    <name>Manufacturer Data</name>
    <group>
      <name>Manufacturer Information</name>
      <description>Manufacturer-provided fixed node description</description>
      <int size="1">
        <name>Version</name>
      </int>
      <string size="12">
        <name>Manufacturer Name</name>
      </string>
      <string size="6">
        <name>Manufacturer Info</name>
      </string>
      <string size="4">
        <name>Hardware Version</name>
      </string>
      <string size="4">
        <name>Software Version</name>
      </string>
    </group>
  </segment>
  <segment origin="0" space="251">
    <name>User Data</name>
    <group offset="0">
      <name>User Data</name>
      <description>Add your own unique node info here</description>
      <int size="1">
        <name>Version</name>
      </int>
      <string size="63">
        <name>User Name</name>
      </string>
      <string size="64">
        <name>User Description</name>
      </string>
    </group>
  </segment>
</cdi>

=== kphannan/OpenLCB/prototypes/mikroPascal/dsPIC33EP256_CommandStation/dsPIC33F_CommandStation.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type='text/xsl' href='http://openlcb.org/trunk/prototypes/xml/xslt/cdi.xsl'?>
<cdi xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://openlcb.org/trunk/prototypes/xml/schema/cdi.xsd">
  <identification>
    <manufacturer>Mustangpeak</manufacturer>
    <model>CS100</model>
    <hardwareVersion>1.0</hardwareVersion>
    <softwareVersion>0.2</softwareVersion>
    <map>
      <relation>
        <property>Description</property>
        <value>Mustangpeak Command Station Node</value>
      </relation>
      <relation>
        <property>Status</property>
        <value>Prototype</value>
      </relation>
    </map>
  </identification>
  <acdi fixed="1" var="1" />
  <segment origin="0" space="253">
    <group offset="1">
      <name>User Data</name>
      <description>Add your own unique node info here</description>
      <string size="20">
        <name>User Name</name>
      </string>
      <string size="40">
        <name>User Description</name>
      </string>
    </group>
    <group>
      <name>Command Station Options</name>
      <description>Configuration options for the LCBricks Command Station</description>
      <int>
        <name>Programming Mode</name>
        <description>Selects the Programming Mode the Command Station will use to write CV's to the decoder</description>
        <map>
          <relation>
            <property>0</property>
            <value>Operation Mode (to a Main Line)</value>
          </relation>
          <relation>
            <property>1</property>
            <value>Auto Programming Mode (to a Programming Track)</value>
          </relation>
          <relation>
            <property>3</property>
            <value>Direct Mode (All Operations)</value>
          </relation>
          <relation>
            <property>4</property>
            <value>Direct Mode (Byte Operations)</value>
          </relation>
          <relation>
            <property>5</property>
            <value>Direct Mode (Bit Operations)</value>
          </relation>
          <relation>
            <property>6</property>
            <value>Paged Mode</value>
          </relation>
        </map>
      </int>
      <int>
        <name>DCC Bus Mode</name>
        <description>Select if this Command Station is the driver or receiver of the DCC bus signal (Damage may occur if more than one Command Station is selected to be a driver on the DCC bus)</description>
        <map>
          <relation>
            <property>0</property>
            <value>Command Station is a DCC Bus Driver</value>
          </relation>
          <relation>
            <property>1</property>
            <value>Command Station is a DCC Bus Receiver</value>
          </relation>
        </map>
      </int>
      <int>
        <name>Output Mode</name>
        <description>Select if this Command Station is a Main Line Node or a Programming Track Node</description>
        <map>
          <relation>
            <property>0</property>
            <value>Command Station drives a Main Line</value>
          </relation>
          <relation>
            <property></property>
            <value>Command Station drives a Programming Track</value>
          </relation>
        </map>
      </int>
    </group>
  </segment>
  <segment origin="0" space="252">
    <group>
      <name>Manufacturer Information</name>
      <description>Manufacturer-provided fixed node description</description>
      <int size="1">
        <name>Version</name>
      </int>
      <string size="12">
        <name>Manufacturer Name</name>
      </string>
      <string size="6">
        <name>Manufacturer Info</name>
      </string>
      <string size="4">
        <name>Hardware Version</name>
      </string>
      <string size="4">
        <name>Software Version</name>
      </string>
    </group>
  </segment>
  <segment origin="0" space="251">
    <group offset="0">
      <name>User Data</name>
      <description>Add your own unique node info here</description>
      <int size="1">
        <name>Version</name>
      </int>
      <string size="20">
        <name>User Name</name>
      </string>
      <string size="40">
        <name>User Description</name>
      </string>
    </group>
  </segment>
</cdi>

=== kphannan/OpenLCB/prototypes/C/OlcbStarLibraries/OlcbIo/cdi.xml
<?xml version='1.0'?>
<?xml-stylesheet type='text/xsl' href='http://openlcb.org/trunk/prototypes/xml/xslt/cdi.xsl'?>
<cdi xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:noNamespaceSchemaLocation='http://openlcb.org/trunk/prototypes/xml/schema/cdi.xsd'>

<identification>
    <manufacturer>OpenLCB</manufacturer>
    <model>OlcbIo</model>
    <hardwareVersion>1.0</hardwareVersion>
    <softwareVersion>0.4</softwareVersion>
</identification>

<segment origin='0' space='253'>
    <group offset='664'>
        <name>User Identification</name>
        <description>Lets the user add his own description</description>
        <string size='20'>
            <name>Node Name</name>
        </string>
        <string size='24'>
            <name>Node Description</name>
        </string>
    </group>
</segment>

<segment origin='12' space='253'>
    <group replication='8'>
        <name>Outputs</name>
        <repname>Output</repname>
        <string size='18' offset='320'>
            <name>Description</name>
        </string>
        <eventid offset='-336' ><!-- forward 320, add 18, so now back 338, then forward 2-->
            <name>Set Event</name>
        </eventid>
        <eventid offset='2' >
            <name>Reset Event</name>
        </eventid>
    </group>
    <group replication='8' offset='2'>  <!-- 2 for end of last event -->
        <name>Inputs</name>
        <repname>Input</repname>
        <string size='16' offset='320'>
            <name>Description</name>
        </string>
        <eventid offset='-336' ><!-- forward 320, add 18, so now back 338, then forward 2-->
            <name>Activation Event</name>
        </eventid>
        <eventid offset='2' >
            <name>Inactivation Event</name>
        </eventid>
    </group>
</segment>

<segment origin='0' space='253'>
    <int size='4'>
        <name>Reset</name>
        <description>Controls reloading and clearing node memory. Board must be restarted for this to take effect.</description>
        <map>
            <relation><property>3998572261</property><value>(No reset)</value></relation>
            <relation><property>3998561228</property><value>User clear: New default EventIDs, blank strings</value></relation>
            <relation><property>0</property><value>Mfg clear: Reset all, including Node ID</value></relation>
        </map>
    </int>
</segment>

</cdi>

=== kphannan/OpenLCB/prototypes/mikroPascal/dsPIC33EP256_CommandStation_Ethernet/dsPIC33F_ProxyNode.xml
<?xml version="1.0" encoding="UTF-8"?><?xml-stylesheet type="text/xsl" href="http://openlcb.org/trunk/prototypes/xml/xslt/cdi.xsl"?><cdi xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://openlcb.org/trunk/specs/schema/cdi.xsd">
  <identification>
    <manufacturer>Mustangpeak</manufacturer>
    <model>PN100</model>
    <hardwareVersion>1.0</hardwareVersion>
    <softwareVersion>0.2</softwareVersion>
    <map>
      <relation>
        <property>Description</property>
        <value>Mustangpeak Train Proxy Node</value>
      </relation>
      <relation>
        <property>Status</property>
        <value>Prototype</value>
      </relation>
    </map>
  </identification>
  <acdi fixed="1" var="1" />
  <segment origin="0" space="253">
    <name>Train Info</name>
    <description>General Information about the Train</description>
    <group offset="1">
      <name>User Data</name>
      <description>Add your own unique node info here</description>
      <string size="63">
        <name>User Name</name>
      </string>
      <string size="64">
        <name>User Description`</name>
      </string>
    </group>
    <string offset="64" size="510">
      <name />
      <description>Enter the URL for the desired custom Function Definition File (FDI) for this Train</description>
    </string>
    <string size="510">
      <name />
      <description>Enter the URL for the desired custom Configuration Definition File (TDI) for this Train</description>
    </string>
  </segment>
  <segment origin="4278190081" space="253">
    <name>CV Access</name>
    <description>Default access to the raw CVs</description>
    <group replication="256">
      <repname>CV Number:</repname>
      <int size="1">
        <min>0</min>
        <max>255</max>
      </int>
    </group>
  </segment>
  <segment origin="0" space="252">
    <group>
      <name>Manufacturer Information</name>
      <description>Manufacturer-provided fixed node description</description>
      <int size="1">
        <name>Version</name>
      </int>
      <string size="12">
        <name>Manufacturer Name</name>
      </string>
      <string size="6">
        <name>Manufacturer Info</name>
      </string>
      <string size="4">
        <name>Hardware Version</name>
      </string>
      <string size="4">
        <name>Software Version</name>
      </string>
    </group>
  </segment>
  <segment origin="0" space="251">
    <group offset="0">
      <name>User Data</name>
      <description>Add your own unique node info here</description>
      <int size="1">
        <name>Version</name>
      </int>
      <string size="63">
        <name>User Name</name>
      </string>
      <string size="64">
        <name>User Description</name>
      </string>
    </group>
  </segment>
</cdi>

=== kphannan/OpenLCB/scratchpads/jkueneman/OPStack/Projects/dsPIC33EPxxxGP502_CAN_NCEBridge/Templates/NMRAnetNceDevice.xml
<?xml version="1.0" encoding="UTF-8"?><?xml-stylesheet type="text/xsl" href="http://openlcb.org/trunk/prototypes/xml/xslt/cdi.xsl"?><cdi xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://openlcb.org/trunk/specs/schema/cdi.xsd">
  <identification>
    <manufacturer>Mustangpeak</manufacturer>
    <model>ND100</model>
    <hardwareVersion>1.0</hardwareVersion>
    <softwareVersion>0.2</softwareVersion>
    <map>
      <relation>
        <property>Description</property>
        <value>Mustangpeak NCE Device Node</value>
      </relation>
      <relation>
        <property>Status</property>
        <value>Prototype</value>
      </relation>
    </map>
  </identification>
  <acdi fixed="1" var="1" />
  <segment origin="0" space="253">
    <name>Options</name>
    <description>Options for the NCE Cab</description>
    <group offset="1">
      <name>User Data</name>
      <description>Add your own unique node info here</description>
      <string size="63">
        <name>User Name</name>
      </string>
      <string size="64">
        <name>User Description</name>
      </string>
    </group>
  </segment>
  <segment origin="0" space="252">
    <name>Manufacturer Data</name>
    <group>
      <name>Manufacturer Information</name>
      <description>Manufacturer-provided fixed node description</description>
      <int size="1">
        <name>Version</name>
      </int>
      <string size="12">
        <name>Manufacturer Name</name>
      </string>
      <string size="6">
        <name>Manufacturer Info</name>
      </string>
      <string size="4">
        <name>Hardware Version</name>
      </string>
      <string size="4">
        <name>Software Version</name>
      </string>
    </group>
  </segment>
  <segment origin="0" space="251">
    <name>User Data</name>
    <group offset="0">
      <name>User Data</name>
      <description>Add your own unique node info here</description>
      <int size="1">
        <name>Version</name>
      </int>
      <string size="63">
        <name>User Name</name>
      </string>
      <string size="64">
        <name>User Description</name>
      </string>
    </group>
  </segment>
</cdi>
