=== kphannan/OpenLCB/prototypes/xml/schema/cdi.xsd
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet href="schema2xhtml.xsl" type="text/xsl"?>

<!-- XML Schema for OpenLCB Configuration Description Information (CDI)     -->

<xs:schema xmlns:xs  ="http://www.w3.org/2001/XMLSchema"
           xmlns:xsi ="http://www.w3.org/2001/XMLSchema-instance"
           >

   <xs:complexType name="mapType">
       <xs:sequence>
              <xs:element name="name" minOccurs="0" maxOccurs="1"/>
              <xs:element name="description" minOccurs="0" maxOccurs="1"/>
              <xs:element name="relation" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="property" minOccurs="1" maxOccurs="1"/>
                    <xs:element name="value" minOccurs="1" maxOccurs="1"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
       </xs:sequence>
    </xs:complexType>

   <xs:complexType name="groupType">
            <xs:sequence>
              <xs:element name="name" minOccurs="0" maxOccurs="1"/>
              <xs:element name="description" minOccurs="0" maxOccurs="1"/>
              <xs:choice minOccurs="0" maxOccurs="unbounded">
                  <xs:annotation>
                    <xs:documentation>
                      Allows any sequence of the contained element types
                    </xs:documentation>
                  </xs:annotation>
                  <xs:element name="group" type="groupType" minOccurs="0" maxOccurs="1"/>
                  <xs:element name="bit" type="bitType" minOccurs="0" maxOccurs="1"/>
                  <xs:element name="int" type="intType" minOccurs="0" maxOccurs="1"/>
                  <xs:element name="eventid" type="eventidType" minOccurs="0" maxOccurs="1"/>
              </xs:choice>
            </xs:sequence>
            <xs:attribute name="offset" type="xs:int" />
            <xs:attribute name="replication" type="xs:int" />
    </xs:complexType>

   <xs:complexType name="eventidType">
            <xs:sequence>
              <xs:element name="name" minOccurs="0" maxOccurs="1"/>
              <xs:element name="description" minOccurs="0" maxOccurs="1"/>
              <xs:element name="map" type="mapType" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
    </xs:complexType>

   <xs:complexType name="intType">
            <xs:sequence>
              <xs:element name="name" minOccurs="0" maxOccurs="1"/>
              <xs:element name="description" minOccurs="0" maxOccurs="1"/>
              <xs:element name="min" minOccurs="0" maxOccurs="1"/>
              <xs:element name="max" minOccurs="0" maxOccurs="1"/>
              <xs:element name="default" minOccurs="0" maxOccurs="1"/>
              <xs:element name="map" type="mapType" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
            <xs:attribute name="size" type="xs:int" />
    </xs:complexType>

   <xs:complexType name="bitType">
            <xs:sequence>
              <xs:element name="name" minOccurs="0" maxOccurs="1"/>
              <xs:element name="description" minOccurs="0" maxOccurs="1"/>
              <xs:element name="map" type="mapType" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
            <xs:attribute name="size" type="xs:int" />
    </xs:complexType>

    <xs:element name="cdi">
      <xs:annotation>
        <xs:documentation>
          This is the schema for Configuration Description Information (cdi)
        </xs:documentation>
      </xs:annotation>
      <xs:complexType>
        <xs:sequence>

          <xs:element name="identification" minOccurs="0" maxOccurs="1">
            <xs:annotation>
              <xs:documentation>
                Common first element to identify the decoder
              </xs:documentation>
            </xs:annotation>
            <xs:complexType>
              <xs:sequence>
                <xs:element name="manufacturer" minOccurs="0" maxOccurs="1"/>
                <xs:element name="model" minOccurs="0" maxOccurs="1"/>
                <xs:element name="hardwareVersion" minOccurs="0" maxOccurs="1"/>
                <xs:element name="softwareVersion" minOccurs="0" maxOccurs="1"/>
                <xs:element name="map" type="mapType" minOccurs="0" maxOccurs="1"/>
              </xs:sequence>
            </xs:complexType>
          </xs:element>

          <xs:element name="segment" minOccurs="0" maxOccurs="unbounded">
            <xs:annotation>
              <xs:documentation>
                Define the contents of a memory space
              </xs:documentation>
            </xs:annotation>
            <xs:complexType>
              <xs:sequence>
                <xs:element name="name" minOccurs="0" maxOccurs="1"/>
                <xs:element name="description" minOccurs="0" maxOccurs="1"/>
                <xs:choice minOccurs="0" maxOccurs="unbounded">
                  <xs:annotation>
                    <xs:documentation>
                      Allows any sequence of the contained element types
                    </xs:documentation>
                  </xs:annotation>
                  <xs:element name="group" type="groupType" minOccurs="0" maxOccurs="1"/>
                  <xs:element name="bit" type="bitType" minOccurs="0" maxOccurs="1"/>
                  <xs:element name="int" type="intType" minOccurs="0" maxOccurs="1"/>
                  <xs:element name="eventid" type="eventidType" minOccurs="0" maxOccurs="1"/>
                </xs:choice>
              </xs:sequence>
              <xs:attribute name="space" type="xs:int" />
              <xs:attribute name="origin" type="xs:int" />
            </xs:complexType>
          </xs:element>

        </xs:sequence>
      </xs:complexType>
    </xs:element>
</xs:schema>

=== kphannan/OpenLCB/prototypes/mikroPascal/dsPIC33EP_CommandStation/dsPIC33F_ProxyNode.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type='text/xsl' href='http://openlcb.org/trunk/prototypes/xml/xslt/cdi.xsl'?>
<cdi xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://openlcb.org/trunk/prototypes/xml/schema/cdi.xsd">
  <identification>
    <manufacturer>Mustangpeak</manufacturer>
    <model>PN100</model>
    <hardwareVersion>1.0</hardwareVersion>
    <softwareVersion>0.2</softwareVersion>
    <map>
      <relation>
        <property>Description</property>
        <value>Mustangpeak Train Proxy Node</value>
      </relation>
      <relation>
        <property>Status</property>
        <value>Prototype</value>
      </relation>
    </map>
  </identification>
  <acdi fixed="1" var="1" />
  <segment origin="0" space="253">
    <group offset="0">
      <name>User Data</name>
      <description>Add your own unique node info here</description>
      <string size="20">
        <name>User Name</name>
      </string>
      <string size="40">
        <name>User Description`</name>
      </string>
    </group>
  </segment>
  <segment origin="0" space="252">
    <group>
      <name>Manufacturer Information</name>
      <description>Manufacturer-provided fixed node description</description>
      <int size="1">
        <name>Version</name>
      </int>
      <string size="12">
        <name>Manufacturer Name</name>
      </string>
      <string size="6">
        <name>Manufacturer Info</name>
      </string>
      <string size="4">
        <name>Hardware Version</name>
      </string>
      <string size="4">
        <name>Software Version</name>
      </string>
    </group>
  </segment>
  <segment origin="0" space="251">
    <group offset="0">
      <name>User Data</name>
      <description>Add your own unique node info here</description>
      <int size="1">
        <name>Version</name>
      </int>
      <string size="20">
        <name>User Name</name>
      </string>
      <string size="40">
        <name>User Description</name>
      </string>
    </group>
  </segment>
  <segment origin="0" space="250">
    <group replication="9">
      <name>Node Effects Definition Information (NEDI)</name>
      <description>Describes Custom Effects for the Train</description>
      <repname>Effect</repname>
      <string size="16">
        <name>Effect Description</name>
        <description>Give the Effect a description to help identify it (0-16 chars)</description>
      </string>
      <string size="16">
        <name>Grouping Name</name>
        <description>Group related Effects by giving them the same Grouping Name (0-16 chars)</description>
      </string>
      <int size="1">
        <name>Latching</name>
        <description>The Effect remains in the enabled state for a predetermined time then toggles to the disabled state</description>
        <map>
          <relation>
            <property>1</property>
            <value>Latching is Enabled</value>
          </relation>
          <relation>
            <property>0</property>
            <value>Latching is Disabled</value>
          </relation>
        </map>
      </int>
      <int size="1">
        <name>Auto Toggle Time</name>
        <description>Seconds before toggling back to the "Disabled" state if not Latching (1-255)</description>
      </int>
    </group>
  </segment>
  <segment origin="0" space="249">
    <group replication="25">
      <name>Node Customization Definition Information (NCDI)</name>
      <description>Describes Customization for the Train and its operation</description>
      <repname>Customization</repname>
      <string size="16">
        <name>Customization Description</name>
        <description>Give the Customization a description to help identify it (0-16 chars)</description>
      </string>
      <string size="16">
        <name>Grouping Name</name>
        <description>Group related Customizations by giving them the same Grouping Name (0-16 chars)</description>
      </string>
      <int size="1">
        <name>Status</name>
        <description>The status of the Customization</description>
        <map>
          <relation>
            <property>0</property>
            <value>Value may not be in sync with the hardware</value>
          </relation>
          <relation>
            <property>1</property>
            <value>Value is known to be in sync with the hardware</value>
          </relation>
          <relation>
            <property>2</property>
            <value>Value needs to be commited to the hardware</value>
          </relation>
        </map>
      </int>
      <int size="1">
        <name>Value</name>
        <description>The value of the Customization</description>
      </int>
    </group>
  </segment>
</cdi>

=== kphannan/OpenLCB/prototypes/mikroPascal/Train_CDI/cdi_16_24_PC.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://openlcb.org/trunk/prototypes/xml/xslt/cdi.xsl"?>
<cdi xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:noNamespaceSchemaLocation='http://openlcb.org/trunk/prototypes/xml/schema/cdi.xsd'>

<identification>
    <manufacturer>TCH Technology</manufacturer>
    <model>OpenLCB 16 in 24 out P/C node Rev B</model>
    <hardwareVersion>1.0.3</hardwareVersion>
    <softwareVersion>0.7.7</softwareVersion>
    <map>
        <relation>
        <property>Description</property>
        <value>TCH Technology OpenLCB Node</value>
        </relation>
        <relation>
        <property>Sold to</property>
        <value>John Doe 03/21/2013</value>
        </relation>
        <relation>
        <property>Status</property>
        <value>Released 01/21/2013</value>
        </relation>
    </map>
</identification>

<segment origin='0' space='253'>
    <group offset='816'>
        <name>User Identification</name>
        <description>Add your own unique node infomation here.   Node Name Max 20 characters.</description>
        <string size='20'>
            <name>Node Name</name>
        </string>
        <string size='30'>
            <name>Node Description</name>
        </string>
    </group>
</segment>

<segment origin='10' space='253'>
    <group replication='24'>
        <name>Outputs</name>
        <repname>Output</repname>
        <string size='16' offset='860'>
            <name>Description</name>
        </string>
        <eventid offset='-874' ><!-- forward 150, add 16, back 166, then forward 2-->
            <name>Activation Event</name>
        </eventid>
        <eventid offset='2' >
            <name>Inactivation Event</name>
        </eventid>
    </group>
    <group replication='16'>
        <name>Inputs</name>
        <repname>Input</repname>
        <string size='16' offset='860'>
            <name>Description</name>
        </string>
        <eventid offset='-874' ><!-- forward 150, add 16, back 166, then forward 2-->
            <name>Set Event</name>
        </eventid>
        <eventid offset='2' >
            <name>Reset Event</name>
        </eventid>
    </group>
</segment>

<segment origin='0' space='253'>
    <int size='4'>
        <name>Reset</name>
        <description>Controls reloading and clearing node memory. Board must be restarted for this to take effect.</description>
        <map>
            <relation><property>3998572261</property><value>(No reset)</value></relation>
            <relation><property>0</property><value>Mfg clear: Reset all, including Node ID</value></relation>
            <relation><property>3998561228</property><value>User clear: New default EventIDs, blank strings </value></relation>
        </map>
    </int>
</segment>

</cdi>

=== kphannan/OpenLCB/prototypes/mikroPascal/dsPIC33EP_XpressnetBridge/NMRAnetXpressnetAdapter.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type='text/xsl' href='http://openlcb.org/trunk/prototypes/xml/xslt/cdi.xsl'?>
<cdi xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://openlcb.org/trunk/prototypes/xml/schema/cdi.xsd">
  <identification>
    <manufacturer>Mustangpeak</manufacturer>
    <model>XA100</model>
    <hardwareVersion>1.0</hardwareVersion>
    <softwareVersion>0.2</softwareVersion>
    <map>
      <relation>
        <property>Description</property>
        <value>Mustangpeak Xpressnet Adapter Node</value>
      </relation>
      <relation>
        <property>Status</property>
        <value>Prototype</value>
      </relation>
    </map>
  </identification>
  <acdi fixed="1" var="1" />
  <segment origin="1" space="253">
    <group offset="1">
      <name>User Data</name>
      <description>Add your own unique node info here</description>
      <string size="20">
        <name>User Name</name>
      </string>
      <string size="40">
        <name>User Description</name>
      </string>
    </group>
  </segment>
  <segment origin="0" space="252">
    <group>
      <name>Manufacturer Information</name>
      <description>Manufacturer-provided fixed node description</description>
      <int size="1">
        <name>Version</name>
      </int>
      <string size="12">
        <name>Manufacturer Name</name>
      </string>
      <string size="6">
        <name>Manufacturer Info</name>
      </string>
      <string size="4">
        <name>Hardware Version</name>
      </string>
      <string size="4">
        <name>Software Version</name>
      </string>
    </group>
  </segment>
  <segment origin="0" space="251">
    <group offset="0">
      <name>User Data</name>
      <description>Add your own unique node info here</description>
      <int size="1">
        <name>Version</name>
      </int>
      <string size="20">
        <name>User Name</name>
      </string>
      <string size="40">
        <name>User Description</name>
      </string>
    </group>
  </segment>
</cdi>
