=== kphannan/OpenLCB/prototypes/xml/schema/fdi.xsd
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet href="schema2xhtml.xsl" type="text/xsl"?>
<!-- XML Schema for OpenLCB Function Description Information (FDI),     -->
<!-- part of the Traction Control Protocol                              -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
   <xs:complexType name="groupType">
      <xs:sequence>
         <xs:element name="name" minOccurs="1" maxOccurs="1"/>
         <xs:element name="description" minOccurs="0" maxOccurs="1"/>
         <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:annotation>
               <xs:documentation>
                  Allows any sequence of the contained element types
               </xs:documentation>
            </xs:annotation>
            <xs:element name="function" type="functionType" minOccurs="0" maxOccurs="1"/>
         </xs:choice>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="functionType">
      <xs:sequence>
         <xs:element name="name" minOccurs="1" maxOccurs="1"/>
         <xs:element name="description" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
      <xs:attribute name="size" type="xs:int" default="1"/>
      <xs:attribute name="kind" type="functionKindType" default="binary"/>
      <xs:attribute name="origin" type="xs:int" use="required">
         <xs:annotation>
            <xs:documentation>
               Starting address of the segment's contents within the memory space.
            </xs:documentation>
         </xs:annotation>
      </xs:attribute>
   </xs:complexType>
   <xs:simpleType name="functionKindType">
      <xs:annotation>
         <xs:documentation>
            Possible values for "kind" attribute of function element.
         </xs:documentation>
      </xs:annotation>
      <xs:restriction base="xs:token">
         <xs:enumeration value="binary"/>
         <xs:enumeration value="analog"/>
      </xs:restriction>
   </xs:simpleType>
   <xs:element name="fdi">
      <xs:annotation>
         <xs:documentation>
            This is the schema for Function Description Information (FDI)
         </xs:documentation>
      </xs:annotation>
      <xs:complexType>
         <xs:sequence>
            <xs:element name="segment" minOccurs="1" maxOccurs="1">
               <xs:annotation>
                  <xs:documentation>
                     Define the contents of a memory space
                  </xs:documentation>
               </xs:annotation>
               <xs:complexType>
                  <xs:sequence>
                     <xs:element name="name" minOccurs="1" maxOccurs="1"/>
                     <xs:element name="description" minOccurs="0" maxOccurs="1"/>
                     <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:annotation>
                           <xs:documentation>
                              Allows any sequence of the contained element types
                           </xs:documentation>
                        </xs:annotation>
                        <xs:element name="group" type="groupType" minOccurs="0" maxOccurs="1"/>
                     </xs:choice>
                  </xs:sequence>
                  <xs:attribute name="space" type="xs:int" use="required">
                     <xs:annotation>
                        <xs:documentation>
                           The decimal number of the address space where the information is found.
                        </xs:documentation>
                     </xs:annotation>
                  </xs:attribute>
                  <xs:attribute name="origin" type="xs:int" default="0">
                     <xs:annotation>
                        <xs:documentation>
                           Starting address of the segment's contents within the memory space.
                        </xs:documentation>
                     </xs:annotation>
                  </xs:attribute>
               </xs:complexType>
            </xs:element>
         </xs:sequence>
      </xs:complexType>
   </xs:element>
</xs:schema>

=== kphannan/OpenLCB/prototypes/mikroPascal/FDI/FDI_Default.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type='text/xsl' href='http://openlcb.org/trunk/prototypes/xml/xslt/fdi.xsl'?>
<fdi xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://openlcb.org/trunk/prototypes/xml/schema/fdi.xsd">
  <segment origin="0" space="250">
    <group replication="29">
      <name>Functions F0-F28</name>
      <description>Generic Function Definition Information</description>
      <function size="1" kind="binary" latch="false">
        <name>F0</name>
        <number>0</number>
      </function>
    </group>
  </segment>
</fdi>

=== kphannan/OpenLCB/scratchpads/jkueneman/OPStack/Common FDI/FDI_Default_NMRA.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type='text/xsl' href='http://openlcb.org/trunk/prototypes/xml/xslt/fdi.xsl'?>
<fdi xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://openlcb.org/trunk/prototypes/xml/schema/fdi.xsd">
  <segment space="250" origin="0">
    <name>Default NMRA Functions</name>
    <description>Generic mapping of the NMRA functions</description>
    <group>
      <name>Functions</name>
      <function>
        <name>F0</name>
      </function>
      <function>
        <name>F1</name>
      </function>
      <function>
        <name>F2</name>
      </function>
      <function>
        <name>F3</name>
      </function>
      <function>
        <name>F4</name>
      </function>
      <function>
        <name>F5</name>
      </function>
      <function>
        <name>F6</name>
      </function>
      <function>
        <name>F7</name>
      </function>
      <function>
        <name>F8</name>
      </function>
      <function>
        <name>F9</name>
      </function>
      <function>
        <name>F10</name>
      </function>
      <function>
        <name>F11</name>
      </function>
      <function>
        <name>F12</name>
      </function>
      <function>
        <name>F13</name>
      </function>
      <function>
        <name>F14</name>
      </function>
      <function>
        <name>F15</name>
      </function>
      <function>
        <name>F16</name>
      </function>
      <function>
        <name>F17</name>
      </function>
      <function>
        <name>F18</name>
      </function>
      <function>
        <name>F19</name>
      </function>
      <function>
        <name>F20</name>
      </function>
      <function>
        <name>F21</name>
      </function>
      <function>
        <name>F22</name>
      </function>
      <function>
        <name>F23</name>
      </function>
      <function>
        <name>F24</name>
      </function>
      <function>
        <name>F25</name>
      </function>
      <function>
        <name>F26</name>
      </function>
      <function>
        <name>F27</name>
      </function>
       <function>
        <name>F28</name>
      </function>
    </group>
  </segment>
</fdi>
